[env]
TERM = "xterm-256color"

[font]
size = 6

[font.bold]
family = "Cozette"
style = "Bold"

[font.italic]
family = "Cozette"
style = "Italic"

[font.normal]
family = "Cozette"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"
[[keyboard.bindings]]
action="SearchPrevious"
key = "P"
mods = "Control|Shift"

[shell]
args = ["--login"]
program = "/bin/fish"
