require('plugins/lazy')

require('plugins/neoformat')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
require('plugins/telescope')
require('plugins/neoformat')
require('plugins/toggleterm')
require('plugins/nvim-dap')
require('plugins/null-ls')
require('plugins/symbols-outline')
require('plugins/lsp_signature')
require('plugins/lualine')
require('plugins/elixir')
require('plugins/octo')
